### ISSUE TITLE
Add comment on already deployed contract

### ISSUE THREAD

**Issue by pcaversaccio** [The-Arbiter/NonReplayable#2]
Maybe it makes sense in the comments to add that if people are just interested in an on-chain oracle that checks for the merge, there is already a deployed contract from me: https://etherscan.io/address/0x17fef0d05ffed818af08ae00bec06b65c4319618

here the gist: https://gist.github.com/pcaversaccio/87b4666b2131ad950bf9ee97573447be

Like that we don't spam the chain with redundant code :-D

**Comment by The-Arbiter** [comment]
Done!
